version: '3.8'

services:
  todo-app:
    # ... (остальное без изменений)
    build: ./
    command: ./wait-for-postgres.sh db ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
    
  db:
    restart: always
    image: postgres:latest
    # --- ИЗМЕНИТЕ ЭТУ ЧАСТЬ ---
    volumes:
    # Замените монтирование локальной папки на именованный том pgdata
    - pgdata:/var/lib/postgresql/data
    # -------------------------
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432

# --- ДОБАВЬТЕ ЭТОТ БЛОК В КОНЕЦ ФАЙЛА ---
volumes:
  pgdata: